pipeline {
    agent any

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/th41ng/QLDA.git', branch: 'main'
            }
        }

        stage('Setup Python') {
            steps {
                bat "C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m venv venv"
                bat "venv\\Scripts\\python -m pip install --upgrade pip"
                bat "venv\\Scripts\\python -m pip install -r requirements.txt"
            }
        }

        stage('Run Unit Tests') {
            steps {
                bat "venv\\Scripts\\python -m pytest tests/ -v"
            }
        }
    }

   post {
    success {
        echo '✅ PASS'
    }
    failure {
        echo '❌ FAIL'
    }
}
}
